[theme]
base = "light"
primaryColor = "#5b3706"
backgroundColor = "#e1cba3"
secondaryBackgroundColor= "#ede4ce"
dataframeHeaderBackgroundColor = "#e9d6a6"
borderColor = "#9f9b94"
showWidgetBorder = true 
textColor = "#703B3B"
font = "sans serif"