[theme]
base = "light"
primaryColor = "#5b3706"
backgroundColor = "#e1cba3"
secondaryBackgroundColor= "#ede4ce"
dataframeHeaderBackgroundColor = "#e9d6a6"
borderColor = "#A1A3A6"
textColor = "#703B3B"
font = "sans serif"